//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ChatAppDBEntities : DbContext
    {
        public ChatAppDBEntities()
            : base("name=ChatAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
    
        public virtual ObjectResult<AllChannels_Result> AllChannels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllChannels_Result>("AllChannels");
        }
    
        public virtual ObjectResult<AllUsers_Result> AllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllUsers_Result>("AllUsers");
        }
    
        public virtual ObjectResult<GetChannelMembers_Result> GetChannelMembers(Nullable<long> channelId)
        {
            var channelIdParameter = channelId.HasValue ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChannelMembers_Result>("GetChannelMembers", channelIdParameter);
        }
    
        public virtual int RegisterUser(string username, string firstname, string lastname, string password, Nullable<System.DateTime> registrationDate)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var registrationDateParameter = registrationDate.HasValue ?
                new ObjectParameter("registrationDate", registrationDate) :
                new ObjectParameter("registrationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegisterUser", usernameParameter, firstnameParameter, lastnameParameter, passwordParameter, registrationDateParameter);
        }
    
        public virtual ObjectResult<GetUserCredentials_Result> GetUserCredentials(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserCredentials_Result>("GetUserCredentials", usernameParameter);
        }
    
        public virtual int DeleteChannelUserMessages(Nullable<long> channelId, string username)
        {
            var channelIdParameter = channelId.HasValue ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(long));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteChannelUserMessages", channelIdParameter, usernameParameter);
        }
    
        public virtual int DeleteMessage(string username, Nullable<long> messageId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("messageId", messageId) :
                new ObjectParameter("messageId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMessage", usernameParameter, messageIdParameter);
        }
    
        public virtual int DeleteUserMessages(string username, string usernameOther)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var usernameOtherParameter = usernameOther != null ?
                new ObjectParameter("usernameOther", usernameOther) :
                new ObjectParameter("usernameOther", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserMessages", usernameParameter, usernameOtherParameter);
        }
    
        public virtual int UpdateMessage(Nullable<long> messageId, string content)
        {
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("messageId", messageId) :
                new ObjectParameter("messageId", typeof(long));
    
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMessage", messageIdParameter, contentParameter);
        }
    
        public virtual ObjectResult<DirectMessages_Result> DirectMessages(string username, string usernameOther, Nullable<int> topN)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var usernameOtherParameter = usernameOther != null ?
                new ObjectParameter("usernameOther", usernameOther) :
                new ObjectParameter("usernameOther", typeof(string));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("topN", topN) :
                new ObjectParameter("topN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DirectMessages_Result>("DirectMessages", usernameParameter, usernameOtherParameter, topNParameter);
        }
    
        public virtual ObjectResult<GetChannelMessages_Result> GetChannelMessages(Nullable<long> channelId, Nullable<int> topN)
        {
            var channelIdParameter = channelId.HasValue ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(long));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("topN", topN) :
                new ObjectParameter("topN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChannelMessages_Result>("GetChannelMessages", channelIdParameter, topNParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> StoreUserMessage(string content, string username, string usernameOther, Nullable<System.DateTime> timeSent)
        {
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var usernameOtherParameter = usernameOther != null ?
                new ObjectParameter("usernameOther", usernameOther) :
                new ObjectParameter("usernameOther", typeof(string));
    
            var timeSentParameter = timeSent.HasValue ?
                new ObjectParameter("timeSent", timeSent) :
                new ObjectParameter("timeSent", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("StoreUserMessage", contentParameter, usernameParameter, usernameOtherParameter, timeSentParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> StoreChannelMessage(string content, string username, Nullable<long> channelId, Nullable<System.DateTime> timeSent)
        {
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var channelIdParameter = channelId.HasValue ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(long));
    
            var timeSentParameter = timeSent.HasValue ?
                new ObjectParameter("timeSent", timeSent) :
                new ObjectParameter("timeSent", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("StoreChannelMessage", contentParameter, usernameParameter, channelIdParameter, timeSentParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> GetChannelMessageNotifications(string username, Nullable<System.DateTime> lastReceived)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var lastReceivedParameter = lastReceived.HasValue ?
                new ObjectParameter("lastReceived", lastReceived) :
                new ObjectParameter("lastReceived", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetChannelMessageNotifications", usernameParameter, lastReceivedParameter);
        }
    
        public virtual ObjectResult<string> GetUserMessageNotifications(string username, Nullable<System.DateTime> lastReceived)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var lastReceivedParameter = lastReceived.HasValue ?
                new ObjectParameter("lastReceived", lastReceived) :
                new ObjectParameter("lastReceived", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserMessageNotifications", usernameParameter, lastReceivedParameter);
        }
    }
}
